version: "3.9"

services:
  backend:
    build: ./backend
    container_name: sso-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: sso-frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend
